import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'], // Поддержка русского
  weight: ['400', '500', '600', '700'], // Нужные начертания
  variable: '--font-montserrat', // CSS переменная
  display: 'swap', // Для производительности
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    icons: {
        icon: { 
            url: '/favicon.svg',
            type: "image/svg+xml" 
        },
    },
    title: "Апогей",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${montserrat.className}`}>
                {children}
            </body>
        </html>
    );
}
